"""initial schema

Revision ID: 9b0821082666
Revises: 
Create Date: 2026-07-27 07:26:47.387952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import necessário: o autogenerate referencia `app.models.player.GUID`
# (o TypeDecorator de UUID portável definido no Módulo 1) pelo caminho
# completo, mas não adiciona a import automaticamente.
import app.models.player


# revision identifiers, used by Alembic.
revision: str = '9b0821082666'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('iso_code', name=op.f('pk_countries'))
    )
    op.create_table('surfaces',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.CheckConstraint("name IN ('hard', 'clay', 'grass', 'carpet')", name=op.f('ck_surfaces_surface_name_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surfaces')),
    sa.UniqueConstraint('name', name=op.f('uq_surfaces_name'))
    )
    op.create_table('tournaments',
    sa.Column('id', app.models.player.GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('grand_slam', 'masters_1000', 'atp_500', 'atp_250', 'challenger', 'itf')", name=op.f('ck_tournaments_tournaments_category_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments')),
    sa.UniqueConstraint('name', name=op.f('uq_tournaments_name'))
    )
    op.create_table('users',
    sa.Column('id', app.models.player.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name=op.f('ck_users_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('players',
    sa.Column('id', app.models.player.GUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country_iso', sa.String(length=2), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('plays', sa.String(length=20), nullable=True),
    sa.Column('turned_pro', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("plays IS NULL OR plays IN ('right-handed', 'left-handed', 'ambidextrous')", name=op.f('ck_players_players_plays_valid')),
    sa.CheckConstraint('height_cm IS NULL OR height_cm BETWEEN 140 AND 230', name=op.f('ck_players_players_height_range')),
    sa.ForeignKeyConstraint(['country_iso'], ['countries.iso_code'], name=op.f('fk_players_country_iso_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('first_name', 'last_name', 'date_of_birth', name='players_identity')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', app.models.player.GUID(), nullable=False),
    sa.Column('user_id', app.models.player.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('tournament_editions',
    sa.Column('id', app.models.player.GUID(), nullable=False),
    sa.Column('tournament_id', app.models.player.GUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('surface_id', sa.SmallInteger(), nullable=False),
    sa.Column('country_iso', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('draw_size', sa.SmallInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('prize_money_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint('draw_size IS NULL OR draw_size IN (16, 32, 64, 128)', name=op.f('ck_tournament_editions_tournament_editions_draw_size_valid')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_tournament_editions_tournament_editions_dates_order')),
    sa.CheckConstraint('prize_money_usd IS NULL OR prize_money_usd >= 0', name=op.f('ck_tournament_editions_tournament_editions_prize_non_negative')),
    sa.CheckConstraint('year BETWEEN 1968 AND 2100', name=op.f('ck_tournament_editions_tournament_editions_year_range')),
    sa.ForeignKeyConstraint(['country_iso'], ['countries.iso_code'], name=op.f('fk_tournament_editions_country_iso_countries')),
    sa.ForeignKeyConstraint(['surface_id'], ['surfaces.id'], name=op.f('fk_tournament_editions_surface_id_surfaces')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_editions_tournament_id_tournaments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_editions')),
    sa.UniqueConstraint('tournament_id', 'year', name='tournament_editions_unique')
    )
    op.create_table('matches',
    sa.Column('id', app.models.player.GUID(), nullable=False),
    sa.Column('tournament_edition_id', app.models.player.GUID(), nullable=False),
    sa.Column('round', sa.String(length=10), nullable=False),
    sa.Column('player1_id', app.models.player.GUID(), nullable=False),
    sa.Column('player2_id', app.models.player.GUID(), nullable=False),
    sa.Column('winner_id', app.models.player.GUID(), nullable=True),
    sa.Column('best_of', sa.SmallInteger(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('player_low_id', app.models.player.GUID(), nullable=False),
    sa.Column('player_high_id', app.models.player.GUID(), nullable=False),
    sa.CheckConstraint("round IN ('R128', 'R64', 'R32', 'R16', 'QF', 'SF', 'F')", name=op.f('ck_matches_matches_round_valid')),
    sa.CheckConstraint("status IN ('scheduled', 'in_progress', 'completed', 'retired', 'walkover')", name=op.f('ck_matches_matches_status_valid')),
    sa.CheckConstraint('best_of IN (3, 5)', name=op.f('ck_matches_matches_best_of_valid')),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name=op.f('ck_matches_matches_duration_positive')),
    sa.CheckConstraint('player1_id <> player2_id', name=op.f('ck_matches_matches_distinct_players')),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], name=op.f('fk_matches_player1_id_players')),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], name=op.f('fk_matches_player2_id_players')),
    sa.ForeignKeyConstraint(['tournament_edition_id'], ['tournament_editions.id'], name=op.f('fk_matches_tournament_edition_id_tournament_editions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], name=op.f('fk_matches_winner_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('player_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', app.models.player.GUID(), nullable=False),
    sa.Column('ranking_date', sa.Date(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.CheckConstraint('points >= 0', name=op.f('ck_player_rankings_player_rankings_points_non_negative')),
    sa.CheckConstraint('rank_position > 0', name=op.f('ck_player_rankings_player_rankings_rank_positive')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_rankings_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_rankings')),
    sa.UniqueConstraint('player_id', 'ranking_date', name='player_rankings_unique')
    )
    op.create_table('simulations',
    sa.Column('id', app.models.player.GUID(), nullable=False),
    sa.Column('user_id', app.models.player.GUID(), nullable=False),
    sa.Column('player1_id', app.models.player.GUID(), nullable=False),
    sa.Column('player2_id', app.models.player.GUID(), nullable=False),
    sa.Column('surface_id', sa.SmallInteger(), nullable=False),
    sa.Column('best_of', sa.SmallInteger(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('player1_win_probability', sa.Float(), nullable=True),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=True),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=True),
    sa.Column('sets_won_distribution', sa.JSON(), nullable=True),
    sa.Column('avg_match_duration_minutes', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name=op.f('ck_simulations_simulations_status_valid')),
    sa.CheckConstraint('best_of IN (3, 5)', name=op.f('ck_simulations_simulations_best_of_valid')),
    sa.CheckConstraint('iterations BETWEEN 1000 AND 1000000', name=op.f('ck_simulations_simulations_iterations_range')),
    sa.CheckConstraint('player1_id <> player2_id', name=op.f('ck_simulations_simulations_distinct_players')),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], name=op.f('fk_simulations_player1_id_players')),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], name=op.f('fk_simulations_player2_id_players')),
    sa.ForeignKeyConstraint(['surface_id'], ['surfaces.id'], name=op.f('fk_simulations_surface_id_surfaces')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_simulations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulations'))
    )
    op.create_table('match_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', app.models.player.GUID(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('player1_games', sa.SmallInteger(), nullable=False),
    sa.Column('player2_games', sa.SmallInteger(), nullable=False),
    sa.Column('tiebreak_p1_points', sa.SmallInteger(), nullable=True),
    sa.Column('tiebreak_p2_points', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('player1_games >= 0', name=op.f('ck_match_sets_match_sets_p1_games_non_negative')),
    sa.CheckConstraint('player2_games >= 0', name=op.f('ck_match_sets_match_sets_p2_games_non_negative')),
    sa.CheckConstraint('set_number BETWEEN 1 AND 5', name=op.f('ck_match_sets_match_sets_number_range')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_sets_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_sets')),
    sa.UniqueConstraint('match_id', 'set_number', name='match_sets_unique')
    )
    op.create_table('match_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', app.models.player.GUID(), nullable=False),
    sa.Column('player_id', app.models.player.GUID(), nullable=False),
    sa.Column('aces', sa.SmallInteger(), nullable=True),
    sa.Column('double_faults', sa.SmallInteger(), nullable=True),
    sa.Column('first_serve_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_serve_points_won_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('second_serve_points_won_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_points_saved', sa.SmallInteger(), nullable=True),
    sa.Column('break_points_faced', sa.SmallInteger(), nullable=True),
    sa.Column('total_points_won', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('aces IS NULL OR aces >= 0', name=op.f('ck_match_statistics_match_statistics_aces_non_negative')),
    sa.CheckConstraint('double_faults IS NULL OR double_faults >= 0', name=op.f('ck_match_statistics_match_statistics_df_non_negative')),
    sa.CheckConstraint('first_serve_pct IS NULL OR first_serve_pct BETWEEN 0 AND 100', name=op.f('ck_match_statistics_match_statistics_first_serve_pct_range')),
    sa.CheckConstraint('first_serve_points_won_pct IS NULL OR first_serve_points_won_pct BETWEEN 0 AND 100', name=op.f('ck_match_statistics_match_statistics_fspw_range')),
    sa.CheckConstraint('second_serve_points_won_pct IS NULL OR second_serve_points_won_pct BETWEEN 0 AND 100', name=op.f('ck_match_statistics_match_statistics_sspw_range')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_statistics_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_statistics_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_statistics')),
    sa.UniqueConstraint('match_id', 'player_id', name='match_statistics_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_statistics')
    op.drop_table('match_sets')
    op.drop_table('simulations')
    op.drop_table('player_rankings')
    op.drop_table('matches')
    op.drop_table('tournament_editions')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tournaments')
    op.drop_table('surfaces')
    op.drop_table('countries')
    # ### end Alembic commands ###
